name: begenchgeldyev

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - backend
    networks:
      - begenchgeldyev-network

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: begench
      POSTGRES_PASSWORD: begench
      POSTGRES_DB: begenchgeldyev
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - begenchgeldyev-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8613:8613"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - begenchgeldyev-network

volumes:
  pgdata:

networks:
  begenchgeldyev-network:
    driver: bridge
